package com.coolerfall.lunarlite.data.db.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "almanac".
 */
public class Almanac {

    private Integer wielding;
    private Integer hseb;
    private String dread;
    private String suit;

    public Almanac() {
    }

    public Almanac(Integer wielding, Integer hseb, String dread, String suit) {
        this.wielding = wielding;
        this.hseb = hseb;
        this.dread = dread;
        this.suit = suit;
    }

    public Integer getWielding() {
        return wielding;
    }

    public void setWielding(Integer wielding) {
        this.wielding = wielding;
    }

    public Integer getHseb() {
        return hseb;
    }

    public void setHseb(Integer hseb) {
        this.hseb = hseb;
    }

    public String getDread() {
        return dread;
    }

    public void setDread(String dread) {
        this.dread = dread;
    }

    public String getSuit() {
        return suit;
    }

    public void setSuit(String suit) {
        this.suit = suit;
    }

}
