package com.anbillon.lunarlite.data.db.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig almanacDaoConfig;

    private final AlmanacDao almanacDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        almanacDaoConfig = daoConfigMap.get(AlmanacDao.class).clone();
        almanacDaoConfig.initIdentityScope(type);

        almanacDao = new AlmanacDao(almanacDaoConfig, this);

        registerDao(Almanac.class, almanacDao);
    }
    
    public void clear() {
        almanacDaoConfig.getIdentityScope().clear();
    }

    public AlmanacDao getAlmanacDao() {
        return almanacDao;
    }

}
